apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: action-shellcheck
  description: |
    GitHub action for ShellCheck
  annotations:
    github.com/project-slug: Tradeshift/action-shellcheck
  tags:
    - github-action
    - fork
spec:
  type: library
  owner: sre
  lifecycle: production
